### PR TITLE
Update versions of all packages, keeping Python at 3.6

### PR DESCRIPTION
**Pull request by fperez**
This is a big update bringing all package versions to their current up to date state. Once it passes CI and goes into staging, we should have the team run some checks online with our actual codes before pushing to prod, as virtually every package changed versions.

I should have done this earlier in the summer - not ideal to be doing this now with the class running! But better now early in the semester, than stay locked in with old versions of quite a few packages for the whole term.

### CODE REVIEW

**Comment by ryanlovett** [comment]
This fails on `jupyter labextension install @jupyter-widgets/jupyterlab-manager` due to missing nodejs. If one adds nodejs==8.11.4, the same command will fail with:
```
> /srv/conda/bin/npm pack @jupyter-widgets/jupyterlab-manager
jupyter-widgets-jupyterlab-manager-0.37.3.tgz

Errored, use --debug for full output:
ValueError:
"@jupyter-widgets/jupyterlab-manager@0.37.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.15.4-0 <0.16.0-0    >=0.18.0-0 <0.19.0-0 @jupyterlab/application
>=1.0.10-0 <2.0.0-0     >=2.0.0-0 <3.0.0-0   @jupyterlab/coreutils
>=0.15.7-0 <0.16.0-0    >=0.18.0-0 <0.19.0-0 @jupyterlab/notebook
>=0.15.4-0 <0.16.0-0    >=0.18.0-0 <0.19.0-0 @jupyterlab/rendermime
>=1.1.4-0 <2.0.0-0      >=3.0.0-0 <4.0.0-0   @jupyterlab/services
```

**Comment by fperez** [comment]
Mmh... gonna have to bug the experts here :)

@jasongrout @ian-r-rose @blink1073 - any tips on what I might be doing wrong? This is a docker image build using [this Dockerfile](https://github.com/berkeley-dsep-infra/data100f18hub/blob/04226f1609c2f2269065735ed1f3e3ef5b194832/user-image/Dockerfile) and this [conda environment](https://github.com/berkeley-dsep-infra/data100f18hub/blob/04226f1609c2f2269065735ed1f3e3ef5b194832/user-image/environment.yml).  I ran the same environment build locally on my laptop and had no issues, it's giving the above errors on Travis.

Thanks for any tips!

**Comment by jasongrout** [comment]
What version of JupyterLab are you using? You might need to install an older version of the widgets manager: https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager#version-compatibility

**Comment by jasongrout** [comment]
According to your environment file, you're using jlab 0.34, so it should work. Perhaps it's picking up the wrong jlab when doing the `jupyter labextension install` command? Can you do `jupyter lab --version` right before `jupyter labextension install` to see what version of jlab it is using? You might also do `jupyter lab path` and `which jupyter-lab` to see exactly what jupyterlab is being invoked.

**Comment by jasongrout** [comment]
(I also think you don't need this line anymore: https://github.com/berkeley-dsep-infra/data100f18hub/blob/04226f1609c2f2269065735ed1f3e3ef5b194832/user-image/Dockerfile#L95 - jlab uses the new config.d-type system the notebook now enables to automatically enable the server extension)

**Comment by blink1073** [comment]
There is a specific jlab 0.34 in the environment file, but that is definitely an older jlab being invoked by `jupyter labexension`.

**Comment by blink1073** [comment]
Also, you'll want to use  `jupyter labextension install @jupyter-widgets/jupyterlab-manager@^0.37` to avoid picking up new versions when JupyterLab 0.35 is released.

**Comment by blink1073** [comment]
I'm not able to make a PR right now, but I'd like to see the output if you add `nodejs` to the conda requirements and use the specific incantation above.

**Comment by fperez** [comment]
Thanks! I just made a few small fixes as per your suggestions above, let's see what happens...

Ah!!! I just realized part of the problem might be a too old miniconda...

Let me update the miniconda path too.

**Comment by fperez** [comment]
Ok, did that, updating to 4.5.11 - let's see if that helps

**Comment by fperez** [comment]
Also added extra diagnostics suggested by @jasongrout.

**Comment by blink1073** [comment]
She's green!

**Comment by fperez** [comment]
Great! Not sure which of the above fixed it, but regardless, good to have a fully updated env.

Huge thanks guys for the quick help.

@ryanlovett, LMK when it's up in the live staging hub and I'll play with it there...

**Comment by fperez** [comment]
Ah never mind, my page was out of date... I see it's merged now, thanks! I'll watch the 2nd Travis build and will play with the live hub when ready.  Thanks @ryanlovett for the quick merge.

**Comment by blink1073** [comment]
Happy to help!

**Comment by ryanlovett** [comment]
@fperez Its live on staging now. Just let me know if you want to merge to prod.

**Pull request merged**
